[tool.poetry]
name = "test-py-pipelines"
version = "0.1.2"
description = ""
authors = ["Marco Enrico Piras <kikkomep@crs4.it>"]
readme = "README.md"
license = "MIT"
keywords = ["test", "pipelines"]

[[tool.poetry.source]]
name = "foo"
url = "https://github.com/kikkomep/test-py-pipelines.git"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
