[tool.poetry]
name = "test-py-pipelines"
version = "0.1.6"
description = ""
authors = ["Marco Enrico Piras <kikkomep@crs4.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
